services:
  pesv-front:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - /app/node_modules
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped 